#ifdef _S_MOD_REMOVE_PRAGMA_ONCE_WARNING_
#else //_S_MOD_REMOVE_PRAGMA_ONCE_WARNING_
#pragma once 
#endif //_S_MOD_REMOVE_PRAGMA_ONCE_WARNING_

//< 상수 정의 부분

#define BUFSIZE 64
#define MAXENEMY 1

//< enum

enum DIRECTION {
	DRT_BACK_RIGHT ,DRT_BACK_LEFT ,DRT_BACK ,DRT_RIGHT,DRT_LEFT ,DRT_FRONT_RIGHT ,DRT_FRONT_LEFT ,DRT_FRONT, DRT_END};